apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: review #Should they all be called app?
# a requires can also be set here if needed
build:
  artifacts:
  - image: reviewservice
    context: .
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: false
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/reviewservice.yaml
    - ./kubernetes-manifests/mongodb-pvc.yaml
    - ./kubernetes-manifests/mongodb-deployment.yaml
profiles:
- name: gcb
  build:
    googleCloudBuild:
      diskSizeGb: 300
      machineType: N1_HIGHCPU_32
      timeout: 4000s